### ISSUE TITLE
Failed to Install the dStar

### ISSUE THREAD

**Issue by firdausya-nc** [nworbde/dStar#10]
I try to install the dStar after successfully cloning it, but it is failed to installed after entering the constants installation step. What should I do to fix it? Thank you for your answers
![error_installation_2](https://user-images.githubusercontent.com/81305403/112309844-70e6dc80-8cd6-11eb-8cf7-d6ce8d70b22a.png)
![error_installing_1](https://user-images.githubusercontent.com/81305403/112309847-72b0a000-8cd6-11eb-812e-8f70458a233c.png)

**Comment by nworbde** [comment]
Hello,
I’m guessing that you are using the latest version of MESA. What happened is that MESA changed its constants library, so I need to update dStar to match it. I’ve already done this, I just haven’t put it into the main repository yet.  I’ll make an attempt to have that done today.

Thanks,
Ed

**Comment by firdausya-nc** [comment]
Thanks for your help, Ed :)
